### ISSUE TITLE
Tracking Development

### ISSUE THREAD

**Issue by slovanos** [aihpi/ragsst#1]
### Tasklist:

- [x] Refactor core functions (everything except the interface) into a class

- [x] Rag Chat: Handle history with stand alone questions
    - [x] Add standalone query prompt

- [x] Add limited conversation history with deque

- [x] Add retrieval settings to other relevant tabs
    - [x] rag query
    - [x]  rag chat
    - [x] If there is no context for the threshold, inform it.

- [x] Add parameters descriptions

- [x] RagTool Settings tab. Where parameters like, LLM, embeddings model, conversation length,  etc. can be chosen
    - [x] Add "submit" button (that sets the state of the correspondent object members) 
    - [x] List Local Models
    - [x] Pull models
    - [x] Add process info
    - [x] Add delete Collection and Database options
    - [x] Add general processing info

- [x] Check, handle actions, implement and/or remove the buttons: Retry, Undo and Clear

- [x] Add retrieval exports options

- [x] Update initdb conditions

- [x] Update prompt template

- [x] Update file listing to walk subfolders

- [x] Enhance logger. Shift prints to logger

- [x] Refactor to modules

- [x] make_collection: Skip/update embeddings checking files name and then hash

- [x] UI: Prettier print of the metadata

- [x] Update Readme
    - [x] Include Logo and RAG gif
    - [x] Add Retrieval Settings description
    - [x] Include LOG_LEVEL information

- [x] Update sample docs

- [x] Clean mockups
